using Microsoft.Extensions.Options;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using NetXP.CompositionRoots;
using NetXP.DependencyInjection;
using NetXP.DependencyInjection.Implementations.StructureMaps;
using NetXP.ImageGeneratorAI;
using NetXP.ImageGeneratorAI.LeonardoAI;
using NetXP.Processes;
using NetXP.Processes.Implementations;
using StructureMap;
using System;
using System.Linq;
using System.Net.Http;
using System.Net;
using System.Threading;
using Moq.Contrib.HttpClient;
using Newtonsoft.Json;
using NetXP.TTSs.OpenTTS;
using NetXP.TTS;
using System.Collections.Generic;
using System.IO;
using NetXP.TTSs.ElevenLabs;
using Moq.Protected;
using System.Threading.Tasks;

namespace NetXP.NetCoreUnitTest.Processes.Implementations
{
    [TestClass]
    public class ElevenLabsTest
    {
        public DependencyInjection.IContainer container;
        private Mock<IOptions<TTSElevenlabsOptions>> opt;

        [TestInitialize]
        public void Initialize()
        {
            //Init options
            this.opt = new Mock<IOptions<TTSElevenlabsOptions>>();
            opt.Setup(o => o.Value).Returns(new TTSElevenlabsOptions
            {
                URL = "http://localhost/",
                APIKey = "testkey",
                GetVoicesUri = "v1/voices",
                TextToSpeechUri = "v1/text-to-speech/{0}" //{0} Id voice
            });
        }

        [TestMethod]
        public void GetTTSVoices()

        {
            //Init http
            var handler = new Mock<HttpMessageHandler>();
            var client = handler.CreateClient();
            client.BaseAddress = new Uri(opt.Object.Value.URL);
            var clientFactory = new Mock<IHttpClientFactory>();
            clientFactory.Setup(o => o.CreateClient(string.Empty)).Returns(client);

            var dynamicPostResult = JsonConvert.DeserializeObject<Root>(jsonPostResultTTSVoices);

            var response = new HttpResponseMessage() { Content = new StringContent(jsonPostResultTTSVoices) };
            handler.Protected().Setup<Task<HttpResponseMessage>>
                ("SendAsync"
                , ItExpr.IsAny<HttpRequestMessage>()
                , ItExpr.IsAny<CancellationToken>()
                ).ReturnsAsync(response);

            var leoAI = new TTSEvenLabs(opt.Object, clientFactory.Object);

            //Do
            var result = leoAI.GetTTSVoices().Result;

            //Assert
            Assert.AreEqual(result.Count, dynamicPostResult.voices.Count);
        }

        [TestMethod]
        public void Convert()
        {
            //Init http
            var handler = new Mock<HttpMessageHandler>();
            var client = handler.CreateClient();
            client.BaseAddress = new Uri(opt.Object.Value.URL);
            var clientFactory = new Mock<IHttpClientFactory>();
            clientFactory.Setup(o => o.CreateClient(string.Empty)).Returns(client);

            var expectedFile = File.ReadAllBytes("audio.wav");

            handler.SetupAnyRequest()
                  .ReturnsResponse(new MemoryStream(expectedFile, 0, expectedFile.Length));

            //Init options
            var leoAI = new TTSs.ElevenLabs.TTSEvenLabs(opt.Object, clientFactory.Object);

            //Do
            var result = leoAI.Convert(new TTSConvertOption
            {
                Text = "Hola, probando.",
                Voice = new TTSVoice
                {
                    Id = "ZQe5CZNOzWyzPSCn5a3c",
                    ModelId = "eleven_multilingual_v1"
                }
            }).Result;

            var responseFile = result.File.ToArray();

            //Assert
            Assert.AreEqual(responseFile.Length, expectedFile.Length);
            Assert.IsTrue(responseFile.SequenceEqual(expectedFile));
        }

        //This string was generated by Leonardo.AI API
        public string jsonPostResultTTSVoices = @"{
    ""voices"": [
        {
            ""voice_id"": ""21m00Tcm4TlvDq8ikWAM"",
            ""name"": ""Rachel"",
            ""samples"": null,
            ""category"": ""premade"",
            ""fine_tuning"": {
                ""language"": null,
                ""is_allowed_to_fine_tune"": false,
                ""fine_tuning_requested"": false,
                ""finetuning_state"": ""not_started"",
                ""verification_attempts"": null,
                ""verification_failures"": [],
                ""verification_attempts_count"": 0,
                ""slice_ids"": null,
                ""manual_verification"": null,
                ""manual_verification_requested"": false
            },
            ""labels"": {
                ""accent"": ""american"",
                ""description"": ""calm"",
                ""age"": ""young"",
                ""gender"": ""female"",
                ""use_case"": ""narration""
            },
            ""description"": null,
            ""preview_url"": ""https://storage.googleapis.com/eleven-public-prod/premade/voices/21m00Tcm4TlvDq8ikWAM/df6788f9-5c96-470d-8312-aab3b3d8f50a.mp3"",
            ""available_for_tiers"": [],
            ""settings"": null,
            ""sharing"": null,
            ""high_quality_base_model_ids"": []
        },
        {
            ""voice_id"": ""2EiwWnXFnvU5JabPnv8n"",
            ""name"": ""Clyde"",
            ""samples"": null,
            ""category"": ""premade"",
            ""fine_tuning"": {
                ""language"": null,
                ""is_allowed_to_fine_tune"": false,
                ""fine_tuning_requested"": false,
                ""finetuning_state"": ""not_started"",
                ""verification_attempts"": null,
                ""verification_failures"": [],
                ""verification_attempts_count"": 0,
                ""slice_ids"": null,
                ""manual_verification"": null,
                ""manual_verification_requested"": false
            },
            ""labels"": {
                ""accent"": ""american"",
                ""description"": ""war veteran"",
                ""age"": ""middle aged"",
                ""gender"": ""male"",
                ""use_case"": ""video games""
            },
            ""description"": null,
            ""preview_url"": ""https://storage.googleapis.com/eleven-public-prod/premade/voices/2EiwWnXFnvU5JabPnv8n/65d80f52-703f-4cae-a91d-75d4e200ed02.mp3"",
            ""available_for_tiers"": [],
            ""settings"": null,
            ""sharing"": null,
            ""high_quality_base_model_ids"": [
                ""eleven_multilingual_v1""
            ]
        },
        {
            ""voice_id"": ""AZnzlk1XvdvUeBnXmlld"",
            ""name"": ""Domi"",
            ""samples"": null,
            ""category"": ""premade"",
            ""fine_tuning"": {
                ""language"": null,
                ""is_allowed_to_fine_tune"": false,
                ""fine_tuning_requested"": false,
                ""finetuning_state"": ""not_started"",
                ""verification_attempts"": null,
                ""verification_failures"": [],
                ""verification_attempts_count"": 0,
                ""slice_ids"": null,
                ""manual_verification"": null,
                ""manual_verification_requested"": false
            },
            ""labels"": {
                ""accent"": ""american"",
                ""description"": ""strong"",
                ""age"": ""young"",
                ""gender"": ""female"",
                ""use_case"": ""narration""
            },
            ""description"": null,
            ""preview_url"": ""https://storage.googleapis.com/eleven-public-prod/premade/voices/AZnzlk1XvdvUeBnXmlld/508e12d0-a7f7-4d86-a0d3-f3884ff353ed.mp3"",
            ""available_for_tiers"": [],
            ""settings"": null,
            ""sharing"": null,
            ""high_quality_base_model_ids"": []
        },
        {
            ""voice_id"": ""CYw3kZ02Hs0563khs1Fj"",
            ""name"": ""Dave"",
            ""samples"": null,
            ""category"": ""premade"",
            ""fine_tuning"": {
                ""language"": null,
                ""is_allowed_to_fine_tune"": false,
                ""fine_tuning_requested"": false,
                ""finetuning_state"": ""not_started"",
                ""verification_attempts"": null,
                ""verification_failures"": [],
                ""verification_attempts_count"": 0,
                ""slice_ids"": null,
                ""manual_verification"": null,
                ""manual_verification_requested"": false
            },
            ""labels"": {
                ""accent"": ""british-essex"",
                ""description"": ""conversational"",
                ""age"": ""young"",
                ""gender"": ""male"",
                ""use_case"": ""video games""
            },
            ""description"": null,
            ""preview_url"": ""https://storage.googleapis.com/eleven-public-prod/premade/voices/CYw3kZ02Hs0563khs1Fj/872cb056-45d3-419e-b5c6-de2b387a93a0.mp3"",
            ""available_for_tiers"": [],
            ""settings"": null,
            ""sharing"": null,
            ""high_quality_base_model_ids"": [
                ""eleven_multilingual_v1""
            ]
        }]}
        ";


    }
}
