# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
 -  job: 'NetXP_DependencyInjection_Impelementations_LamarDI'
    pool:
      vmImage: ubuntu-latest

    variables:
    - name: env
      ${{ if eq(variables['Build.SourceBranchName'], 'devel') }}:
        value: beta

    steps:
    - task: UseDotNet@2
      inputs:
        version: 6.x
    
    - task: CmdLine@2
      inputs:
        script: |
          cd
          dir
          echo  '$(System.DefaultWorkingDirectory)'
          

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '$(System.DefaultWorkingDirectory)/NetXP.DependencyInjection.Implementations.Lamar/NetXP.DependencyInjection.Implementations.LamarDI.csproj'
        
    - task: DotNetCoreCLI@2
      displayName: "dotnet build"
      inputs:
        command: 'build'
        projects: 'NetXP.DependencyInjection.Implementations.Lamar/NetXP.DependencyInjection.Implementations.LamarDI.csproj'
        arguments: '-c Release'
        
    - task: NuGetCommand@2
      inputs:
        command: 'pack'
        packagesToPack: '$(System.DefaultWorkingDirectory)/NetXP.DependencyInjection.Implementations.Lamar/NetXP.DependencyInjection.Implementations.LamarDI.csproj'
        versioningScheme: 'off'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        