///////////////////////////////////////////////////////////
//  IServerProtocolSP.cs
//  Implementation of the Interface IServerProtocolSP
//  Generated by Enterprise Architect
//  Created on:      16-Apr-2015 12:45:40 AM
//  Original author: unrea-sh2
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using NetXP.NetStandard;
using NetXP.NetStandard.Network.i;
using System.Net;
using System.Threading.Tasks;

namespace NetXP.NetStandard.Network.LittleJsonProtocol
{
    public interface IServerLJP
    {
        void Listen(IPAddress oIPAddress, int iPort);
        Task<IClientLJP> Accept();

    }//end IServerProtocolSP
}
