using Microsoft.Extensions.Options;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using NetXP.CompositionRoots;
using NetXP.DependencyInjection;
using NetXP.DependencyInjection.Implementations.StructureMaps;
using NetXP.ImageGeneratorAI;
using NetXP.ImageGeneratorAI.LeonardoAI;
using NetXP.Processes;
using NetXP.Processes.Implementations;
using StructureMap;
using System;
using System.Linq;
using System.Net.Http;
using System.Net;
using System.Threading;
using Moq.Contrib.HttpClient;
using Newtonsoft.Json;

namespace NetXP.NetCoreUnitTest.Processes.Implementations
{
    [TestClass]
    public class ImageGeneratorAIAITests
    {
        public DependencyInjection.IContainer container;

        [TestMethod]
        public void GenerateAI()
        {
            //Init options
            var opt = new Mock<IOptions<ImageGeneratorAIOptions>>();
            opt.Setup(o => o.Value).Returns(new ImageGeneratorAIOptions { Token = "test" });

            //Init http
            var handler = new Mock<HttpMessageHandler>();
            var client = handler.CreateClient();

            //This string was generated by Leonardo.AI API
            var jsonPostResult = "{\"sdGenerationJob\":{\"generationId\":\"ad4dc7e2-0cee-4a04-89e0-85e284d587b0\"}}";

            var dynamicPostResult = JsonConvert.DeserializeObject<SdGenerationJobRoot>(jsonPostResult);
            handler.SetupAnyRequest()
                   .ReturnsResponse(jsonPostResult);

            var clientFactory = new Mock<IHttpClientFactory>();
            clientFactory.Setup(o => o.CreateClient()).Returns(client);

            var leoAI = new ImageGeneratorAILeonardoAI(opt.Object, clientFactory.Object);

            //Do
            var result = leoAI.Generate(new OptionsImageGenerator
            {
                Prompt = "Test",
                //LeonardoCreative:  6bef9f1b-29cb-40c7-b9df-32b51c1f67d3
                //LeonardoSelect:    cd2b2a15-9760-4174-a5ff-4d2925057376
                //LeonardoSignature: 291be633-cb24-434f-898f-e662799936ad
                ModelId = "6bef9f1b-29cb-40c7-b9df-32b51c1f67d3",
                //Aspect ratio de 9:16 (To full vertical screen)
                Width = 832,
                Height = 1472,
                NumImages = 1,
                ExtraOptions = new { AnyOtherOptionEspecificForTheAPI = "Test" }
            }).Result;

            //Assert
            Assert.AreEqual(result.Id, dynamicPostResult.SdGenerationJob.GenerationId);
        }

        [TestMethod]
        public void GetImages()
        {
            //Init options
            var opt = new Mock<IOptions<ImageGeneratorAIOptions>>();
            opt.Setup(o => o.Value).Returns(new ImageGeneratorAIOptions { Token = "test" });

            //Init http
            var handler = new Mock<HttpMessageHandler>();
            var client = handler.CreateClient();

            var jsonPost = "{\"generations_by_pk\":{\"generated_images\":[{\"url\":\"https://cdn.leonardo.ai/users/22155d31-658d-4b4f-9870-80245919790e/generations/b1fab176-8111-41ae-94a5-5e7f682989b8/Leonardo_Creative_Beautiful_girl_taking_picture_in_the_bathroo_0.jpg\",\"nsfw\":false,\"id\":\"70407bf8-3259-48f3-9a15-088ad7370aac\",\"likeCount\":0,\"generated_image_variation_generics\":[]},{\"url\":\"https://cdn.leonardo.ai/users/22155d31-658d-4b4f-9870-80245919790e/generations/b1fab176-8111-41ae-94a5-5e7f682989b8/Leonardo_Creative_Beautiful_girl_taking_picture_in_the_bathroo_1.jpg\",\"nsfw\":false,\"id\":\"b3f2cd39-50e2-4e48-a963-a1f1cba3aec9\",\"likeCount\":0,\"generated_image_variation_generics\":[]},{\"url\":\"https://cdn.leonardo.ai/users/22155d31-658d-4b4f-9870-80245919790e/generations/b1fab176-8111-41ae-94a5-5e7f682989b8/Leonardo_Creative_Beautiful_girl_taking_picture_in_the_bathroo_2.jpg\",\"nsfw\":false,\"id\":\"b39ec0a6-fa86-426a-8c9b-a5aaeee1e782\",\"likeCount\":0,\"generated_image_variation_generics\":[]},{\"url\":\"https://cdn.leonardo.ai/users/22155d31-658d-4b4f-9870-80245919790e/generations/b1fab176-8111-41ae-94a5-5e7f682989b8/Leonardo_Creative_Beautiful_girl_taking_picture_in_the_bathroo_3.jpg\",\"nsfw\":false,\"id\":\"c09cd4c1-39ce-4b9a-a0ba-a3be45deee69\",\"likeCount\":0,\"generated_image_variation_generics\":[]}],\"modelId\":\"6bef9f1b-29cb-40c7-b9df-32b51c1f67d3\",\"prompt\":\"Beautifulgirltakingpictureinthebathroom\",\"negativePrompt\":\"\",\"imageHeight\":512,\"imageWidth\":512,\"inferenceSteps\":30,\"seed\":123292160,\"public\":false,\"scheduler\":\"EULER_DISCRETE\",\"sdVersion\":\"v2\",\"status\":\"COMPLETE\",\"presetStyle\":null,\"initStrength\":null,\"guidanceScale\":7,\"id\":\"b1fab176-8111-41ae-94a5-5e7f682989b8\",\"createdAt\":\"2023-06-28T02:00:08.058\"}}";
            //Init options

            var dynamicPostResult = JsonConvert.DeserializeObject<GenerateImageLeonardoAIRoot>(jsonPost);
            handler.SetupAnyRequest()
                   .ReturnsResponse(jsonPost);

            var clientFactory = new Mock<IHttpClientFactory>();
            clientFactory.Setup(o => o.CreateClient()).Returns(client);

            var leoAI = new ImageGeneratorAILeonardoAI(opt.Object, clientFactory.Object);

            //Do
            var result = leoAI.GetImages(new ResultGenerate { }).Result;

            //Assert
            Assert.AreEqual(dynamicPostResult.generations_by_pk.generated_images.Length, 4);
        }

        [TestMethod]
        public void RemoveImages()
        {
            //Init options
            var opt = new Mock<IOptions<ImageGeneratorAIOptions>>();
            opt.Setup(o => o.Value).Returns(new ImageGeneratorAIOptions { Token = "test" });

            //Init http
            var handler = new Mock<HttpMessageHandler>();
            var client = handler.CreateClient();

            var jsonPost = "{\"generations_by_pk\":{\"generated_images\":[{\"url\":\"https://cdn.leonardo.ai/users/22155d31-658d-4b4f-9870-80245919790e/generations/b1fab176-8111-41ae-94a5-5e7f682989b8/Leonardo_Creative_Beautiful_girl_taking_picture_in_the_bathroo_0.jpg\",\"nsfw\":false,\"id\":\"70407bf8-3259-48f3-9a15-088ad7370aac\",\"likeCount\":0,\"generated_image_variation_generics\":[]},{\"url\":\"https://cdn.leonardo.ai/users/22155d31-658d-4b4f-9870-80245919790e/generations/b1fab176-8111-41ae-94a5-5e7f682989b8/Leonardo_Creative_Beautiful_girl_taking_picture_in_the_bathroo_1.jpg\",\"nsfw\":false,\"id\":\"b3f2cd39-50e2-4e48-a963-a1f1cba3aec9\",\"likeCount\":0,\"generated_image_variation_generics\":[]},{\"url\":\"https://cdn.leonardo.ai/users/22155d31-658d-4b4f-9870-80245919790e/generations/b1fab176-8111-41ae-94a5-5e7f682989b8/Leonardo_Creative_Beautiful_girl_taking_picture_in_the_bathroo_2.jpg\",\"nsfw\":false,\"id\":\"b39ec0a6-fa86-426a-8c9b-a5aaeee1e782\",\"likeCount\":0,\"generated_image_variation_generics\":[]},{\"url\":\"https://cdn.leonardo.ai/users/22155d31-658d-4b4f-9870-80245919790e/generations/b1fab176-8111-41ae-94a5-5e7f682989b8/Leonardo_Creative_Beautiful_girl_taking_picture_in_the_bathroo_3.jpg\",\"nsfw\":false,\"id\":\"c09cd4c1-39ce-4b9a-a0ba-a3be45deee69\",\"likeCount\":0,\"generated_image_variation_generics\":[]}],\"modelId\":\"6bef9f1b-29cb-40c7-b9df-32b51c1f67d3\",\"prompt\":\"Beautifulgirltakingpictureinthebathroom\",\"negativePrompt\":\"\",\"imageHeight\":512,\"imageWidth\":512,\"inferenceSteps\":30,\"seed\":123292160,\"public\":false,\"scheduler\":\"EULER_DISCRETE\",\"sdVersion\":\"v2\",\"status\":\"COMPLETE\",\"presetStyle\":null,\"initStrength\":null,\"guidanceScale\":7,\"id\":\"b1fab176-8111-41ae-94a5-5e7f682989b8\",\"createdAt\":\"2023-06-28T02:00:08.058\"}}";
            //Init options

            var dynamicPostResult = JsonConvert.DeserializeObject<GenerateImageLeonardoAIRoot>(jsonPost);
            handler.SetupAnyRequest()
                   .ReturnsResponse(jsonPost);

            var clientFactory = new Mock<IHttpClientFactory>();
            clientFactory.Setup(o => o.CreateClient()).Returns(client);

            var leoAI = new ImageGeneratorAILeonardoAI(opt.Object, clientFactory.Object);

            //Do
            var result = leoAI.GetImages(new ResultGenerate { }).Result;

            //Assert
            Assert.AreEqual(dynamicPostResult.generations_by_pk.generated_images.Length, 4);
        }



    }
}
